# Generated by Django 2.2.11 on 2020-05-28 13:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="verzoek",
            old_name="interactiedatum",
            new_name="registratiedatum",
        ),
        migrations.AddField(
            model_name="verzoek",
            name="aangevulde_verzoek",
            field=models.ForeignKey(
                blank=True,
                help_text="URL-referentie naar het (eerdere) VERZOEK dat door dit VERZOEK wordt aangevuld.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aanvullende_verzoek",
                to="datamodel.Verzoek",
            ),
        ),
        migrations.AddField(
            model_name="verzoek",
            name="in_te_trekken_verzoek",
            field=models.ForeignKey(
                blank=True,
                help_text="URL-referentie naar het (eerdere) VERZOEK dat door dit VERZOEK wordt verzocht ingetrokken te worden.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intrekkende_verzoek",
                to="datamodel.Verzoek",
            ),
        ),
        migrations.AlterField(
            model_name="objectverzoek",
            name="object",
            field=models.URLField(
                help_text="URL-referentie naar het gerelateerde OBJECT (in een andere API).",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="verzoek",
            name="tekst",
            field=models.TextField(
                blank=True,
                help_text="Een toelichting die inhoudelijk het VERZOEK van de KLANT beschrijft.",
            ),
        ),
        migrations.AlterField(
            model_name="verzoek",
            name="voorkeurskanaal",
            field=models.CharField(
                blank=True,
                help_text="Het communicatiekanaal dat voor opvolging van het VERZOEK de voorkeur heeft van de KLANT.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="verzoekproduct",
            name="product",
            field=models.URLField(
                blank=True,
                help_text="URL-referentie naar het PRODUCT (in de Producten en Diensten API).",
                max_length=1000,
            ),
        ),
        migrations.CreateModel(
            name="KlantVerzoek",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "klant",
                    models.URLField(
                        help_text="URL-referentie naar een KLANT (in Klanten API)",
                        max_length=1000,
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("belanghebbende", "Belanghebbende"),
                            ("initiator", "Initiator"),
                            ("mede_initiator", "Mede-initiator"),
                        ],
                        help_text="Rol van de KLANT bij het VERZOEK.",
                        max_length=100,
                    ),
                ),
                (
                    "indicatie_machtiging",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gemachtigde", "Gemachtigde"),
                            ("machtiginggever", "Machtiginggever"),
                        ],
                        help_text="Indicatie machtiging",
                        max_length=100,
                    ),
                ),
                (
                    "verzoek",
                    models.ForeignKey(
                        help_text="URL-referentie naar het VERZOEK.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datamodel.Verzoek",
                    ),
                ),
            ],
        ),
    ]
