# Generated by Django 2.2.11 on 2020-05-28 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0003_move_klant_data"),
    ]

    operations = [
        migrations.RemoveField(model_name="verzoek", name="klant",),
    ]
