# Generated by Django 2.2.11 on 2020-05-28 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0003_move_klant_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verzoek",
            name="klant",
        ),
        migrations.AlterField(
            model_name="verzoek",
            name="registratiedatum",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="De datum en het tijdstip waarop het VERZOEK is geregistreerd.",
            ),
        ),
    ]
