# Generated by Django 2.2.11 on 2020-05-28 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0004_auto_20200528_1324"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="klantverzoek",
            options={
                "verbose_name": "klantverzoek",
                "verbose_name_plural": "klantverzoeken",
            },
        ),
        migrations.AlterField(
            model_name="klantverzoek",
            name="rol",
            field=models.CharField(
                blank=True,
                choices=[
                    ("belanghebbende", "Belanghebbende"),
                    ("initiator", "Initiator"),
                    ("mede-initiator", "Mede-initiator"),
                ],
                help_text="Rol van de KLANT bij het VERZOEK.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="verzoek",
            name="aangevulde_verzoek",
            field=models.OneToOneField(
                blank=True,
                help_text="URL-referentie naar het (eerdere) VERZOEK dat door dit VERZOEK wordt aangevuld.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aanvullende_verzoek",
                to="datamodel.Verzoek",
            ),
        ),
        migrations.AlterField(
            model_name="verzoek",
            name="in_te_trekken_verzoek",
            field=models.OneToOneField(
                blank=True,
                help_text="URL-referentie naar het (eerdere) VERZOEK dat door dit VERZOEK wordt verzocht ingetrokken te worden.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intrekkende_verzoek",
                to="datamodel.Verzoek",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="klantverzoek", unique_together={("verzoek", "klant")},
        ),
    ]
