# Generated by Django 2.2.11 on 2020-05-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0004_auto_20200528_1324"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="klantverzoek",
            options={
                "verbose_name": "klantverzoek",
                "verbose_name_plural": "klantverzoeken",
            },
        ),
        migrations.AlterUniqueTogether(
            name="klantverzoek", unique_together={("verzoek", "klant")},
        ),
    ]
