# Generated by Django 2.2.11 on 2020-05-28 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0005_auto_20200528_1332"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verzoek",
            name="aangevulde_verzoek",
            field=models.OneToOneField(
                blank=True,
                help_text="URL-referentie naar het (eerdere) VERZOEK dat door dit VERZOEK wordt aangevuld.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aanvullende_verzoek",
                to="datamodel.Verzoek",
            ),
        ),
        migrations.AlterField(
            model_name="verzoek",
            name="in_te_trekken_verzoek",
            field=models.OneToOneField(
                blank=True,
                help_text="URL-referentie naar het (eerdere) VERZOEK dat door dit VERZOEK wordt verzocht ingetrokken te worden.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intrekkende_verzoek",
                to="datamodel.Verzoek",
            ),
        ),
    ]
