# Inspired by https://docs.docker.com/compose/django/
version: '3.4'

services:
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=${DB_USER:-verzoeken}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-verzoeken}
  web:
    build: .
    image: vngr/verzoeken-api
    environment:
      - DJANGO_SETTINGS_MODULE=verzoeken.conf.docker
      - SECRET_KEY=${SECRET_KEY}
      - DB_USER=${DB_USER:-verzoeken}
      - DB_PASSWORD=${DB_PASSWORD:-verzoeken}
    ports:
      - 8000:8000
    depends_on:
      - db
